{% set name = "runs" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/runs-{{ version }}.tar.gz
  sha256: 9dc1815e2895cfb3a48317b173b9f1eac9ba5549b36a847b5cc60c3bf82ecef1

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python
    - poetry-core
    - pip
  run:
    - python
    - xmod

test:
  imports:
    - runs
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Cannot run upstream tests due to lack of 'tdir' package
    # - pytest -v test_runs.py
  requires:
    - pip

about:
  home: https://github.com/rec/runs
  summary: Run a block of text as a subprocess
  description: runs has improved versions of call(), check_call(), check_output(), and run() from Python's
    subprocess module that handle multiple commands and blocks of text, fix some defects, and add some features.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/rec/runs
  doc_url: https://github.com/rec/runs/blob/main/README.rst

extra:
  recipe-maintainers:
    - nicornk
