{% set name = "runs" %}
{% set version = "1.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cca304b631dbefec598c7bfbcfb50d6feace6d3a968734b67fd42d3c728f5a05

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<310]

requirements:
  host:
    - python
    - uv-build >=0.9.0,<0.10.0
    - pip
  run:
    - python
    - xmod

test:
  imports:
    - runs
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Cannot run upstream tests due to lack of 'tdir' package
    # - pytest -v test_runs.py
  requires:
    - pip

about:
  home: https://github.com/rec/runs
  summary: Run a block of text as a subprocess
  description: runs has improved versions of call(), check_call(), check_output(), and run() from Python's
    subprocess module that handle multiple commands and blocks of text, fix some defects, and add some features.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/rec/runs
  doc_url: https://github.com/rec/runs/blob/main/README.rst

extra:
  recipe-maintainers:
    - nicornk
